### ISSUE TITLE
How to use in android google chrome

### ISSUE THREAD

**Issue by teeddcs** [dalchandra/Chegg_Skip_Extension#5]
I want to use the extension in google chrome. When I try to install it, there is no option for extension in the setting. Is any way to use this extension in google chrome on smartphones.

**Comment by dalchandra** [comment]
In smartphones, most browsers do not support extensions. There is some browser that supports google chrome extensions on smartphones. Kiwi is one of them. The procedure is given in the readme file.

**Comment by teeddcs** [comment]
ok, thanks.
